// Code generated by "stringer -type=MessageID"; DO NOT EDIT.

package mcp

import "strconv"

const _MessageID_name = "McpStartupMcpCharCreateMcpCreateGameMcpJoinGameMcpGameListMcpGameInfoMcpCharLogonMcpCharDeleteMcpRequestLadderDataMcpMOTDMcpCancelGameCreateMcpCreateQueueMcpCharRankMcpCharListMcpCharUpgradeMcpCharList2"

var _MessageID_index = [...]uint8{0, 10, 23, 36, 47, 58, 69, 81, 94, 114, 121, 140, 154, 165, 176, 190, 202}

func (i MessageID) String() string {
	i -= 1
	if i >= MessageID(len(_MessageID_index)-1) {
		return "MessageID(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _MessageID_name[_MessageID_index[i]:_MessageID_index[i+1]]
}
